### ISSUE TITLE
problem with compilation

### ISSUE THREAD

**Issue by max578** [linsalrob/fastq-pair#3]
I am attemting to install fastq_pair locally and my system doesn't allow cmake version higher than 3.0.2. As a result, it seems imposible to compile fastq_pair: "CMake error at CMakeLists.txt:1 (cmake_minimum_required): CMake 3.6 or higher required. You are running version 3.0.2"

Any alternative ways to compile?

**Comment by johned0** [comment]
For such a simple CMakeLists.txt you should be able to just modify the following line :
cmake_minimum_required(VERSION 3.6)
Alternatively, just run the following command in build :
gcc ../*.c -o fastq_pair
Then install the executable in /bin.

**Comment by mbelmadani** [comment]
Just wanted to point out that I had to add the `-std=gnu99` flag for it to work on my machine, using gcc 4.8.5 on CENTOS 7 in case this is useful to anyone.

i.e. `# gcc -std=gnu99 ../*.c -o fastq_pair`

**Comment by linsalrob** [comment]
Terrific, thank you.

**Comment by splaisan** [comment]
plain or as above do not work for me under ubuntu 16
any idea to make this build?

```
gcc -std=gnu99 ../*.c -o fastq_pair
/tmp/ccF5E9lw.o: In function `main':
test_gzip.c:(.text+0x0): multiple definition of `main'
/tmp/cc3jO8M3.o:main.c:(.text+0x79): first defined here
collect2: error: ld returned 1 exit status
```

```
Linux gbw-s-pacbio01 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by linsalrob** [comment]
You may need to amend this command slightly since `test_gzip.c` also has a `main()` method.

This alternate command: 
```
gcc -std=gnu99   ../main.c ../robstr.c ../fastq_pair.c ../is_gzipped.c  -o fastq_pair
```

will compile the code
